#!/bin/bash


set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=dror@raspberrypi
readonly TARGET_PATH=/tmp/juiced
readonly TARGET_ARCH=aarch64-unknown-linux-musl
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/juiced

cargo build --release --target=${TARGET_ARCH}
rsync -avP ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
#ssh -t ${TARGET_HOST} strace -o /tmp/l ${TARGET_PATH}
