[package]
name = "juiced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.4.0"
linux-embedded-hal = "0.3.0"
rust_gpiozero = "0.2.0"
spidev = "0.5.0"
