[package]
name = "mcp3xxx-eh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3"
embedded-hal-mock = "0.7"
embedded-hal = "0.2"