[package]
name = "juicelib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3"
rust_gpiozero = "0.2.0"
spidev = "0.5.0"
rppal = "0.14.1"
rand = "0.8"
rust-fsm = "0.6"